# Generated by Django 4.1.4 on 2023-03-08 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(help_text="Название проекта", max_length=256),
                ),
                (
                    "project_description",
                    models.CharField(help_text="Описание проекта", max_length=1024),
                ),
                (
                    "project_head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_project_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SprintModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sprint",
                    models.CharField(help_text="Описание спринта", max_length=1024),
                ),
                (
                    "sprint_create",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата/время создания спринта"
                    ),
                ),
                (
                    "sprint_start",
                    models.DateTimeField(help_text="Дата/время начала спринта"),
                ),
                (
                    "sprint_end",
                    models.DateTimeField(help_text="Дата/время завершения спринта"),
                ),
                (
                    "sprint_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_sprint",
                        to="task_manager_app.projectmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(help_text="Описание задачи", max_length=1024),
                ),
                (
                    "task_is_Done",
                    models.BooleanField(
                        default=False, help_text="Статус выполнения задачи"
                    ),
                ),
                (
                    "task_create",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Дата/время создания задачи"
                    ),
                ),
                (
                    "task_completed",
                    models.DateTimeField(
                        blank=True, help_text="Дата/время завершения задачи", null=True
                    ),
                ),
                (
                    "task_plan",
                    models.DateTimeField(
                        blank=True, help_text="Плановая дата исполнения", null=True
                    ),
                ),
                ("task_attach", models.FileField(help_text="Вложение", upload_to="")),
                (
                    "task_author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_task_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task_implementer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sprint_task",
                        to="task_manager_app.sprintmodel",
                    ),
                ),
                (
                    "task_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_task",
                        to="task_manager_app.projectmodel",
                    ),
                ),
            ],
        ),
    ]
