# Generated by Django 4.1.4 on 2023-03-08 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_manager_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="task_sprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_task",
                to="task_manager_app.sprintmodel",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_implementer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_task_implementer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
