# Generated by Django 4.1.4 on 2023-03-08 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task_manager_app", "0002_taskmodel_task_sprint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmodel",
            name="project_head",
            field=models.ForeignKey(
                blank=True,
                help_text="Руководитель проекта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_project_head",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_author",
            field=models.ForeignKey(
                blank=True,
                help_text="Автор задачи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_task_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_implementer",
            field=models.ForeignKey(
                blank=True,
                help_text="Исполнитель задачи",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_task_implementer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Проект",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_task",
                to="task_manager_app.projectmodel",
            ),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="task_sprint",
            field=models.ForeignKey(
                blank=True,
                help_text="Спринт",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sprint_task",
                to="task_manager_app.sprintmodel",
            ),
        ),
    ]
