# Generated by Django 4.1.4 on 2023-03-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager_app", "0003_alter_projectmodel_project_head_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprintmodel",
            name="sprint_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Проект",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_sprint",
                to="task_manager_app.projectmodel",
            ),
        ),
    ]
