# Generated by Django 4.1.7 on 2023-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager_app", "0004_alter_sprintmodel_sprint_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="task_attach",
            field=models.FileField(
                blank=True, help_text="Вложение", null=True, upload_to=""
            ),
        ),
    ]
