# Generated by Django 4.1.7 on 2023-03-10 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager_app", "0005_alter_taskmodel_task_attach"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sprintmodel",
            name="sprint_project",
        ),
    ]
