# Generated by Django 4.1.7 on 2023-03-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager_app", "0006_remove_sprintmodel_sprint_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprintmodel",
            name="sprint_project",
            field=models.ForeignKey(
                blank=True,
                help_text="Проект",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_sprint",
                to="task_manager_app.projectmodel",
            ),
        ),
    ]
